### ISSUE TITLE
Problem with geolocator

### ISSUE THREAD

**Issue by Joee8** [yusriltakeuchi/polymaker#9]
After installing the packege and run my app to test, I recive the  message below in the debug console. I look into it and aparrently is a problem with geolocator v8.0.0 and in v8.0.1 that is not a problem but I cannot update the library. So I hope you can I get some help with this.

[AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/geolocator-8.0.0/lib/geolocator.dart:54:11](): Error: No named parameter with the name 'forceAndroidLocationManager'.
          forceAndroidLocationManager: forceAndroidLocationManager);
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by OkomoJacob** [comment]
Hello @Joee8 .
I as well did the same thing you did.
Set-up the env. as required and when I tested the app, I got the same error.
If I downgrade geolocator to v8.0.0 as indicated, the same error below appears. But that error [was fixed in higher versions of geolocator](https://stackoverflow.com/questions/70343204/flutter-geolocator-error-no-named-parameter-with-the-name-forceandroidlocat) as discussed in this link.

```bash
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-8.0.0/lib/geolocator.dart:54:11: Error: No named parameter with the name 'forceAndroidLocationManager'.
          forceAndroidLocationManager: forceAndroidLocationManager);
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
```
- Kindly @yusriltakeuchi help me ensure that `polymaker` works with with geolocator.

**Comment by yusriltakeuchi** [comment]
Hello @OkomoJacob , @Joee8, maybe you can try version ^1.0.3 from this package. I just fixed it

**Comment by OkomoJacob** [comment]
- Ok, I've looked at it. It has got some great updates esp. in the [scores](https://pub.dev/packages/polymaker/score). I'll try it out and get back to you.
- Thanks @yusriltakeuchi for the efforts

**Comment by yusriltakeuchi** [comment]
@OkomoJacob  let me know again if it works, and I will close this issue

**Comment by OkomoJacob** [comment]
- Yes, I've just confirmed now it works, thank you so much.
You can close the issues.
